[pytest]
testpaths = tests
# Ignore a specific test file. 
norecursedirs = tests/test_scratch 
addopts = -n auto --durations=10 --ignore=tests/test_pomp/test_pomp_dpop.py --ignore=tests/test_pomp/test_pomp_train_dpop.py  --ignore=tests/test_models/test_measles_001d.py --ignore=tests/test_ctmc_multinom.py
